Repository mozilla-ai/any-agent, pull requests merged in 2025-04, with the labels that each got.

#76 70 support managed agents with langchain
  .github/workflows/tests.yaml
  pyproject.toml
  src/any_agent/frameworks/langchain.py
  src/any_agent/frameworks/openai.py
  tests/integration/test_load_and_run_agent.py
  tests/integration/test_load_and_run_multi_agent.py
  tests/unit/frameworks/test_langchain.py
Labels: frameworks

#118 tests: Allow to run integration tests via `workflow_dispatch`.
  .github/workflows/tests.yaml
Labels: testing

#103 refactor(frameworks): Implement `_load_tools` in base class.
  src/any_agent/frameworks/agno.py
  src/any_agent/frameworks/any_agent.py
  src/any_agent/frameworks/google.py
  src/any_agent/frameworks/langchain.py
  src/any_agent/frameworks/llama_index.py
  src/any_agent/frameworks/openai.py
  src/any_agent/frameworks/smolagents.py
  tests/integration/test_load_and_run_agent.py
  tests/integration/test_mcp.py
  tests/unit/frameworks/test_openai.py
  tests/unit/tools/test_unit_mcp.py
Labels: tools

#123 docs: Drop `AgentFramework` usage.
  README.md
  docs/evaluation.md
  docs/index.md
  docs/instructions.md
  docs/tools.md
  docs/tracing.md
Labels: documentation

#131 tests(mcp): Use dumb tool instead of `search_web`.
  tests/integration/test_mcp.py
Labels: testing

#136 fix(tracing): Include framework name in output file.
  src/any_agent/tracing.py
  tests/integration/test_load_and_run_agent.py
Labels: tracing

#157 chore: Enable and fix pydocstyle (D) rules.
  pyproject.toml
  src/any_agent/evaluation/evaluate.py
  src/any_agent/evaluation/evaluators/CheckpointEvaluator.py
  src/any_agent/evaluation/evaluators/HypothesisEvaluator.py
  src/any_agent/evaluation/evaluators/LLMEvaluator.py
  src/any_agent/evaluation/evaluators/QuestionAnsweringSquadEvaluator.py
  src/any_agent/evaluation/evaluators/schemas.py
  src/any_agent/evaluation/test_case.py
  src/any_agent/frameworks/any_agent.py
  src/any_agent/telemetry/base.py
  src/any_agent/telemetry/langchain_telemetry.py
  src/any_agent/telemetry/llama_index_telemetry.py
  src/any_agent/telemetry/openai_telemetry.py
  src/any_agent/telemetry/smolagents_telemetry.py
  src/any_agent/tools/__init__.py
  src/any_agent/tools/mcp/__init__.py
  src/any_agent/tools/mcp/frameworks/__init__.py
  src/any_agent/tools/mcp/frameworks/agno.py
  src/any_agent/tools/mcp/frameworks/google.py
  src/any_agent/tools/mcp/frameworks/langchain.py
  src/any_agent/tools/mcp/frameworks/llama_index.py
  src/any_agent/tools/mcp/frameworks/openai.py
  src/any_agent/tools/mcp/frameworks/smolagents.py
  src/any_agent/tools/mcp/mcp_server.py
  src/any_agent/tools/user_interaction.py
  src/any_agent/tools/web_browsing.py
  src/any_agent/tools/wrappers.py
  src/any_agent/tracing.py
  tests/integration/test_wrap_tools.py
  tests/unit/tools/test_unit_mcp.py
  tests/unit/tools/test_unit_wrappers.py
Labels: maintenance

#153 feat: initial test refactor for google and agno mcp servers
  tests/__init__.py
  tests/conftest.py
  tests/docs/__init__.py
  tests/integration/__init__.py
  tests/unit/__init__.py
  tests/unit/frameworks/__init__.py
  tests/unit/tools/__init__.py
  tests/unit/tools/mcp/__init__.py
  tests/unit/tools/mcp/conftest.py
  tests/unit/tools/mcp/test_unit_agno_mcp.py
  tests/unit/tools/mcp/test_unit_all_mcp.py
  tests/unit/tools/mcp/test_unit_google_mcp.py
  tests/unit/tools/mcp/test_unit_langchain_mcp_sse.py
  tests/unit/tools/mcp/test_unit_llama_index_mcp.py
  tests/unit/tools/mcp/test_unit_openai_mcp.py
  tests/unit/tools/mcp/test_unit_smolagents_mcp.py
Labels: testing

#173 fix(docs): Use `python` in code blocks to enusre `mktestdocs` runs.
  README.md
  docs/index.md
  tests/docs/test_all.py
Labels: testing
