Repository mozilla-ai/any-agent, pull requests merged in 2025-05, with the labels that each got.

#193 docs(tinyagent): Add example with mcp.
  docs/frameworks/tinyagent.md
  docs/index.md
Labels: documentation

#200 chore(deps): Bump `agno>=1.4.4`.
  pyproject.toml
Labels: maintenance

#212 docs: Revisit API Reference.
  docs/agents.md
  docs/api.md
  docs/api/agent.md
  docs/api/config.md
  docs/api/tools.md
  docs/api/tracing.md
  docs/frameworks/tinyagent.md
  docs/tools.md
  docs/tracing.md
  mkdocs.yml
  src/any_agent/config.py
  src/any_agent/frameworks/agno.py
  src/any_agent/frameworks/any_agent.py
  src/any_agent/frameworks/google.py
  src/any_agent/frameworks/langchain.py
  src/any_agent/frameworks/llama_index.py
  src/any_agent/frameworks/openai.py
  src/any_agent/frameworks/smolagents.py
  src/any_agent/frameworks/tinyagent.py
  src/any_agent/tools/__init__.py
  src/any_agent/tools/mcp/__init__.py
  src/any_agent/tools/mcp/frameworks/agno.py
  src/any_agent/tools/mcp/frameworks/google.py
  src/any_agent/tools/mcp/frameworks/langchain.py
  src/any_agent/tools/mcp/frameworks/llama_index.py
  src/any_agent/tools/mcp/frameworks/openai.py
  src/any_agent/tools/mcp/frameworks/smolagents.py
  src/any_agent/tools/mcp/frameworks/tinyagent.py
  src/any_agent/tools/mcp/mcp_connection.py
  src/any_agent/tools/mcp/mcp_server.py
  src/any_agent/tools/wrappers.py
  src/any_agent/tracing/trace.py
  tests/integration/test_load_and_run_agent.py
  tests/integration/test_load_and_run_multi_agent.py
  tests/unit/frameworks/test_openai.py
  tests/unit/tools/mcp/conftest.py
  tests/unit/tools/mcp/test_unit_agno_mcp.py
  tests/unit/tools/mcp/test_unit_all_mcp.py
  tests/unit/tools/mcp/test_unit_google_mcp.py
  tests/unit/tools/mcp/test_unit_langchain_mcp_sse.py
  tests/unit/tools/mcp/test_unit_llama_index_mcp.py
  tests/unit/tools/mcp/test_unit_openai_mcp.py
  tests/unit/tools/mcp/test_unit_smolagents_mcp.py
  tests/unit/tracing/test_unit_processors.py
Labels: documentation

#230 fix(AgnoMCPConnection): Pass `include_tools=None` if no tools.
  src/any_agent/tools/mcp/frameworks/agno.py
  tests/unit/tools/mcp/conftest.py
  tests/unit/tools/mcp/test_unit_agno_mcp.py
Labels: tools

#270 Fix docs: default agent in smolagents is ToolCallingAgent
  docs/frameworks/smolagents.md
Labels: documentation

#340 fix(tracing): Show final answer in the console.
  src/any_agent/tracing/exporter.py
  tests/assets/AGNO_trace.html
  tests/assets/AGNO_trace.json
  tests/assets/GOOGLE_trace.html
  tests/assets/GOOGLE_trace.json
  tests/assets/LANGCHAIN_trace.html
  tests/assets/LANGCHAIN_trace.json
  tests/assets/LLAMA_INDEX_trace.html
  tests/assets/LLAMA_INDEX_trace.json
  tests/assets/OPENAI_trace.html
  tests/assets/OPENAI_trace.json
  tests/assets/SMOLAGENTS_trace.html
  tests/assets/SMOLAGENTS_trace.json
  tests/assets/TINYAGENT_trace.html
  tests/assets/TINYAGENT_trace.json
  tests/snapshots/__snapshots__/test_trace.ambr
  tests/unit/tracing/test_unit_exporter.py
Labels: tracing

#363 feat(docs): Simplify `nav`.
  docs/agents/frameworks/agno.md
  docs/agents/frameworks/google_adk.md
  docs/agents/frameworks/langchain.md
  docs/agents/frameworks/llama_index.md
  docs/agents/frameworks/openai.md
  docs/agents/frameworks/smolagents.md
  docs/agents/frameworks/tinyagent.md
  docs/agents/index.md
  docs/agents/tools.md
  docs/api/logging.md
  docs/index.md
  docs/instructions.md
  docs/logging.md
  docs/serving.md
  docs/tools.md
  mkdocs.yml
  src/any_agent/config.py
Labels: documentation

#399 fix(tests): Make sure tinyagent eval traces are not included in the c…
  src/any_agent/frameworks/any_agent.py
  tests/integration/test_load_and_run_agent.py
Labels: testing
